const genres = [
    "Sci-fi",
    "Action",
    "Adventure",
    "Romance",
    "Drama",
    "Noir",
    "Fiction",
    "Narrative",
    "Novel",
    "Mystery",
    "Horror",
    "Fantasy",
    "Thriller",
    "Horror Fiction",
    "Memoir",
    "Poetry",
    "Graphic Novel",
    "Comic",
    "Anime",
    "History",
    "Detective",
]